---
- name: install role
  hosts: localhost
  become: yes

#  roles:
#  - role: httpd
  tasks:
    - name: Touch a file, using symbolic modes to set the permissions (equivalent to 0644)
      ansible.builtin.file:
        path: /etc/foo.conf
        state: touch
        mode: u=rw,g=r,o=r
