---
- name: install role
  hosts: localhost
  become: yes

#  roles:
#  - role: httpd
  tasks:
    - name: install req
      ansible.builtin.command: ansible-galaxy install pradeepkumar027.httpd   
  
    - name: include role
      include_role:
        name:  pradeepkumar027.httpd
