---
- name: install role
  hosts: localhost
  become: yes
  
  tasks:
    - name: install req
      ansible.builtin.command: ansible-galaxy install -r requirements.yml -p roles/
    - name: install pip
    
  
    - name: include role
      include_role:
        name:  pradeepkumar027.httpd