---
- name: install req
  ansible.builtin.command: ansible-galaxy install -r requirements.yml -p roles/
  
- name: include role
  include_role:
    name:  datadog.dd
  vars:
    datadog_api_key: ""
    datadog_site: "datadoghq.eu"
